// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsNAvPrqt-GfyahVnYBJfuWOc7shJKHxA',
    appId: '1:936593739098:android:578f0e9495a49e0f8b3763',
    messagingSenderId: '936593739098',
    projectId: 'my-backyard-944b1',
    storageBucket: 'my-backyard-944b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRlLta5d2rybxDlYvLVKvixxlqGiB1vdU',
    appId: '1:936593739098:ios:371f6c31053051ce8b3763',
    messagingSenderId: '936593739098',
    projectId: 'my-backyard-944b1',
    storageBucket: 'my-backyard-944b1.appspot.com',
    androidClientId:
        '467263379214-6inubl3lne9cumgpfcnrfn5h6h2j9fhc.apps.googleusercontent.com',
    iosClientId:
        '936593739098-mefs8s2o13908fftp6jfknsg1hhgtl0f.apps.googleusercontent.com',
    iosBundleId: 'com.celect.mybackyardapp',
  );
}
