name: month_year_picker
description: The month year picker inspired by the Flutter's date picker design.
version: 0.2.0+3
homepage: https://github.com/zulfahmi93/month-year-picker

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=2.10.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^1.0.0
